# Generated by Django 3.0 on 2020-09-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Contado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacontado',
            name='total',
            field=models.PositiveIntegerField(help_text='Ingresar solo números enteros'),
        ),
    ]
