# Generated by Django 3.0 on 2020-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Contado', '0002_auto_20200913_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacontado',
            name='total',
            field=models.PositiveIntegerField(default=0, help_text='Ingresar solo números enteros'),
        ),
    ]
