# Generated by Django 3.0 on 2020-10-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Contado', '0004_informes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos'),
        ),
    ]
