# Generated by Django 3.0 on 2020-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Contado', '0005_auto_20201007_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacontado',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
