# Generated by Django 3.0 on 2020-08-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Municipio', '0002_auto_20200805_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingresar solo los nombres', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Ingresar solo los apellidos', max_length=50, verbose_name='Apellidos')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(help_text='Ejemplo: 01/01/1991', verbose_name='Fecha de nacimiento')),
                ('cui', models.CharField(help_text='Código que se encuentra en el DPI de cada persona', max_length=17, verbose_name='CUI')),
                ('codigo', models.CharField(help_text='Ejemplo: EMP-001', max_length=10, verbose_name='Código de vendedor')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de Residencia')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Municipio.Municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='NumeroTelefonico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Celular'), ('P', 'Particular'), ('L', 'Laboral'), ('R', 'Residencial'), ('O', 'Otro')], default='C', help_text='Elegir el tipo de número telefónico. Ej. Celular', max_length=1, verbose_name='Tipo número telefónico')),
                ('numero', models.PositiveIntegerField(help_text='Solo ingresar números', verbose_name='Número de Teléfono')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendedores.Vendedor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Número de teléfono del vendedor',
                'verbose_name_plural': 'Números telefónicos de vendedores',
                'db_table': 'telefonosvendedores',
                'unique_together': {('numero',)},
            },
        ),
    ]
