# Generated by Django 3.0 on 2020-09-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numerotelefonico',
            options={'verbose_name': 'Número de teléfono del vendedor', 'verbose_name_plural': 'Agenda telefónica de vendedores'},
        ),
    ]
