# Generated by Django 3.0 on 2020-08-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Credito', '0002_auto_20200817_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventacredito',
            name='engache',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Enganche Q'),
        ),
    ]
