# Generated by Django 3.0 on 2020-09-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20200805_2036'),
        ('Ventas_Credito', '0003_detalleventacredito_engache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('relacion', models.CharField(choices=[('A', 'Personal'), ('F', 'Familiar'), ('L', 'Laboral')], default='F', max_length=1, verbose_name='Relación con el Cliente')),
                ('numero', models.PositiveIntegerField(help_text='Solo ingresar números', verbose_name='Número de Teléfono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Cliente', verbose_name='Cliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas_Credito.VentaCredito', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'db_table': 'referencia',
            },
        ),
    ]
