# Generated by Django 3.0 on 2020-09-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Credito', '0004_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencia',
            name='cliente',
        ),
    ]
