# Generated by Django 3.0 on 2020-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Credito', '0006_auto_20200915_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fecha_inicio', models.DateField(help_text='Fecha donde iniciará la búsqueda', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha donde se finalizará la búsqueda', verbose_name='Fecha de fin')),
                ('mes', models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='1', help_text='Mes que corresponde al informe a generar', max_length=2, verbose_name='Mes')),
            ],
            options={
                'verbose_name': 'Informe mensual',
                'verbose_name_plural': 'Informes mensuales',
                'db_table': 'informe_mensual_credito',
            },
        ),
    ]
