# Generated by Django 3.0 on 2020-10-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Credito', '0007_informes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informes',
            options={'verbose_name': 'Informe mensual, trimestral, anual', 'verbose_name_plural': 'Informes mensuales, trimestrales, anuales'},
        ),
    ]
