# Generated by Django 3.0 on 2020-10-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas_Credito', '0009_auto_20201008_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacredito',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
