# Generated by Django 3.0 on 2020-08-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('nombre', 'departamento')},
        ),
    ]
