# Generated by Django 3.0 on 2020-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cobros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='saldo',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo Actual Q.'),
        ),
    ]
