# Generated by Django 3.0 on 2020-10-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cobros', '0002_auto_20200930_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='cuota',
            field=models.PositiveIntegerField(verbose_name='Cuota'),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='saldo',
            field=models.PositiveIntegerField(default=0, verbose_name='Saldo Actual'),
        ),
    ]
