# Generated by Django 3.0 on 2020-08-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_auto_20200805_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Referencia')),
                ('relacion', models.CharField(choices=[('A', 'Amigo'), ('F', 'Familiar'), ('L', 'Compañero de trabajo')], default='F', max_length=1, verbose_name='Relación')),
                ('numero', models.PositiveIntegerField(help_text='Solo ingresar números', verbose_name='Número de Teléfono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'db_table': 'referencia',
            },
        ),
    ]
