# Generated by Django 3.0 on 2020-08-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Referencias', '0001_initial'),
        ('Ventas_Credito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventas_Credito.VentaCredito', verbose_name='Venta'),
        ),
    ]
