# Generated by Django 3.0 on 2020-08-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20200807_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_2pagos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio en 2 Pagos Q'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_3pagos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio en 3 Pagos Q'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_contado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio de Contado Q'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio Costo Q'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_plazos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio a Plazos Q'),
        ),
    ]
