# Generated by Django 3.0 on 2020-08-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_auto_20200817_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_2pagos',
            field=models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Precio para 2 pagos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_3pagos',
            field=models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Precio para 3 pagos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_contado',
            field=models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Precio de contado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_costo',
            field=models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Precio al costo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_plazos',
            field=models.PositiveIntegerField(help_text='Solo ingresar números enteros positivos', verbose_name='Precio a plazos'),
        ),
    ]
