# Generated by Django 3.0 on 2020-09-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20200901_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agregarexistencia',
            options={'verbose_name': 'Ingreso de existencias', 'verbose_name_plural': 'Ingresos de existencias'},
        ),
    ]
