# Generated by Django 3.0 on 2020-08-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Municipio', '0002_auto_20200805_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingresar solo los nombres', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Ingresar solo los apellidos', max_length=50, verbose_name='Apellidos')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(help_text='Ejemplo: 01/01/1991', verbose_name='Fecha de nacimiento')),
                ('cui', models.CharField(help_text='Código que se encuentra en el DPI de cada persona', max_length=17, verbose_name='CUI')),
                ('nit', models.CharField(help_text='Ejemplo: 1234567-8', max_length=100, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección de Residencia')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Municipio.Municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='NumeroTelefonico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Elegir el tipo de número telefónico. Ej. Celular', max_length=1, verbose_name='Tipo número telefónico')),
                ('numero', models.PositiveIntegerField(help_text='Solo ingresar números', verbose_name='Número de Teléfono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.Cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Número de teléfono de cliente',
                'verbose_name_plural': 'Números de telefónicos de clientes',
                'db_table': 'telefonosclientes',
                'unique_together': {('numero',)},
            },
        ),
    ]
