# Generated by Django 3.0 on 2020-08-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numerotelefonico',
            options={'verbose_name': 'Número de teléfono de cliente', 'verbose_name_plural': 'Números telefónicos de clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(help_text='Ejemplo: 1234567-8', max_length=11, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='numerotelefonico',
            name='tipo',
            field=models.CharField(choices=[('C', 'Celular'), ('P', 'Particular'), ('L', 'Laboral'), ('R', 'Residencial'), ('O', 'Otro')], default='C', help_text='Elegir el tipo de número telefónico. Ej. Celular', max_length=1, verbose_name='Tipo número telefónico'),
        ),
    ]
