# Generated by Django 3.0 on 2020-09-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Municipio', '0002_auto_20200805_1330'),
        ('Clientes', '0002_auto_20200805_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numerotelefonico',
            options={'verbose_name': 'Número de teléfono de cliente', 'verbose_name_plural': 'Agenda telefónica de clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='municipio',
            field=models.ForeignKey(help_text='Municipio donde se realizó la venta', on_delete=django.db.models.deletion.CASCADE, to='Municipio.Municipio', verbose_name='Ubicación'),
        ),
    ]
