# Generated by Django 3.0 on 2020-10-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_auto_20200930_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
    ]
